---
# Playbook for Kali

## Personalize Kali
- hosts: kali
  roles:
    - ansible-role-vscode-extensions
  tasks:
    ### Configure Gnome settings ###
    - name: Tweak Gnome settings
      command: "gsettings set {{ item }}"
      loop: "{{ gnome_settings }}"

    - name: Get current terminal profile
      command: gsettings get org.gnome.Terminal.ProfilesList default
      changed_when: false
      register: terminal_profile

    # Disable terminal background transparency
    - name: Configure Terminal settings
      command: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout | regex_replace('''') }}/ use-transparent-background false"

    ### Configure tmux ###
    - name: Copy tmux config
      copy:
        src: "files/tmux/.tmux.conf"
        dest: "~/.tmux.conf"
        mode: 0640

    ### Firefox personalization ###
    - name: Get FireFox default profile
      command: firefox-esr -CreateProfile default -headless
      register: firefox_default_profile
      failed_when: "'Success' not in firefox_default_profile.stderr"

    - name: Set firefox_default_profile_dir fact
      set_fact:
        firefox_default_profile_dir: "{{ firefox_default_profile.stderr |
          regex_search('(/.*)/prefs.js', multiline=True) |
          regex_replace('(/.*)/prefs.js', '\\1') }}"

    - name: Create user.js for Firefox user preferences
      copy:
        src: "files/firefox/user.js"
        dest: "{{ firefox_default_profile_dir }}/user.js"
        mode: 0640

    ### SciTE user properties ###
    - name: Copy SciTE user properties
      copy:
        src: "files/scite/.SciTEUser.properties"
        dest: "~/.SciTEUser.properties"
        mode: 0640

    ### VS Code ###
    - name: Ensure ~/.config/Code/User directory exists
      file:
        path: "~/.config/Code/User"
        state: directory
        mode: 0700

    - name: Copy VS Code settings
      copy:
        src: files/vscode/settings.json
        dest: "~/.config/Code/User/settings.json"
        mode: 0640

    ### GDB ###
    - name: Clone GEF repo
      git:
        repo: "https://github.com/hugsy/gef.git"
        dest: "~/gef"
        force: true

    - name: Install optional modules for GEF
      pip:
        name:
          - capstone
          - keystone-engine
          - ropper
          - unicorn
        executable: pip3

    - name: Copy gdb user properties
      copy:
        src: "files/gdb/.gdbinit"
        dest: "~/.gdbinit"
        mode: 0640
